cloudformation:
  - any:
    - "**/templates/*.json"
    - "**/templates/*.template"
    - "**/templates/*.yaml"
    - "**/templates/*.yml"

javascript:
  - any:
    - ./**/*.js
    - ./*.js
    - package-lock.json
    - package.json

poetry:
  - any:
    - poetry.lock
    - poetry.toml

python:
  - any:
    - ./**/*.py
    - ./*.py
    - poetry.lock
    - pyproject.toml
    - setup.cfg

workflows:
  - any:
    - ".github/workflows/*.yml"
