bug:
  - bug/*
  - bugfix/*
  - fix/*
  - hotfix/*

dependencies:
  - depend/*
  - dependabot/*

documentation:
  - docs/*

feature:
  - enhancement/*
  - feat/*
  - feature/*

maintenance:
  - chore/*
  - maint/*
  - maintain/*
  - maintenance/*

patch:
  - bug/*
  - bugfix/*
  - fix/*
  - hotfix/*

release:
  - release/*
