name: PR Labeler


on:
  pull_request_target:


jobs:
  branch:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@v0.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # run-release-drafter:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: release-drafter/release-drafter@v5.15.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
