name: PR Labeler


on:
  pull_request:
    types:
      - opened
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronized


jobs:
  branch:
    name: Branch Name Labeler
    if: |
      github.event_name == 'pull_request' &&
      github.event.action == 'opened' &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler-branch.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  file-change:
    name: File Change Labeler
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          configuration-path: .github/pr-labeler-file-change.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
