name: PR Labeler


on:
  pull_request_target:
    - opened
    - reopened
    - synchronize


jobs:
  run-release-drafter:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
