name: PR Labeler (file change)


on:
  pull_request_target:


jobs:
  file-change:
    name: File Change Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          configuration-path: .github/pr-labeler-file-change.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
