name: PR Labeler


on:
  pull_request_target:


jobs:
  branch:
    name: Branch Name Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler-branch.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # run-release-drafter:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: release-drafter/release-drafter@v5.15.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
