name: PR Labeler


on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize


jobs:
  run-release-drafter:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
