name: PR Labeler (branch)


on:
  pull_request:


jobs:
  branch:
    name: Branch Name Labeler
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler-branch.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
