
name: Assign Author (PR)


on:
  pull_request_target:
    types:
      - opened


jobs:
  assign-author:
    name: Assign Author to PR
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/assign-author@v1
